# --- DB (as you have it) ---
spring.application.name=Phegon-Eccormerce
server.port=2424
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/phegon_ecom
spring.datasource.username=phegon
spring.datasource.password=strong_password_here
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# JWT (as you have it)
secreteJwtString=JbiK186eCi9STF6WWd+f3uBfJG6BQmafMszg9JaEIb6DxpoCzmX1+6cWiLW3fojvXOF33YOX32mh+Q7V7t+DjQ==

aws.s3.access=DUMMY_ACCESS
aws.s3.secret=DUMMY_SECRET
aws.s3.secrete=DUMMY_SECRET
aws.s3.bucket=dummy-bucket
aws.s3.region=ap-south-1
